apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector
spec:
  mode: sidecar
  ports:
    - name: "metrics"
      protocol: TCP
      port: 8888
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: ['0.0.0.0:8888']
      hostmetrics:
        scrapers:
          cpu:
          disk:
          filesystem:
          load:
          memory:
          network:
    exporters:
      logging:
        loglevel: debug
      jaeger:
        endpoint: jaeger-collector.observability.svc:14250
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
        resource_to_telemetry_conversion:
          enabled: true
    processors:
      batch:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [jaeger]
          processors: [batch]
        metrics:
          receivers: [otlp, hostmetrics, prometheus]
          exporters: [logging, prometheus]
          processors: [batch]
